# Generated by Django 5.1.1 on 2024-11-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0007_job_applicants_delete_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='founded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Remote', 'Remote'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid')], max_length=50),
        ),
    ]
