# Generated by Django 5.1.1 on 2024-11-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0009_remove_job_company_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
