# Generated by Django 5.1.1 on 2024-11-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0010_job_company_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='filled_vacancies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancy_limit',
            field=models.IntegerField(default=0),
        ),
    ]
