# Generated by Django 5.1.1 on 2024-11-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0012_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
