# Generated by Django 5.1.1 on 2024-10-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0003_alter_applicant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='user',
        ),
    ]
