# Generated by Django 5.1.1 on 2024-10-01 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0004_remove_applicant_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='username',
            new_name='username1',
        ),
    ]
