# Generated by Django 5.1.1 on 2024-10-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0005_rename_email_applicant_email1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='email1',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='password1',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='username1',
            new_name='username',
        ),
    ]
