# Generated by Django 5.1.1 on 2024-10-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0006_rename_email1_applicant_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
