# Generated by Django 5.1.1 on 2024-10-21 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0007_alter_applicant_password_alter_applicant_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('recruiter_name', models.CharField(max_length=150)),
                ('recruiter_email', models.EmailField(max_length=254)),
                ('recruiter_position', models.CharField(max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Applicant.applicant')),
            ],
        ),
    ]
