# Generated by Django 5.1.1 on 2024-10-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0010_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='password',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
