# Generated by Django 5.1.1 on 2024-10-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0012_applicant_password_alter_applicant_email'),
    ]

    operations = [
    ]
