# Generated by Django 5.1.1 on 2024-10-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0013_auto_20241029_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
