# Generated by Django 5.1.1 on 2024-10-30 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0014_applicant_name'),
        ('job_app', '0007_job_applicants_delete_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Applicant.applicant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.job')),
            ],
        ),
    ]
