# Generated by Django 5.1.1 on 2024-11-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0015_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('review', 'Review'), ('interview', 'Interview'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='review', max_length=10),
        ),
    ]
