# Generated by Django 5.1.1 on 2024-11-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0017_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
