# Generated by Django 5.1.1 on 2024-11-05 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0018_application_interview_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='interview_datetime',
            new_name='interview_date_time',
        ),
    ]
