# Generated by Django 5.1.1 on 2024-11-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0019_rename_interview_datetime_application_interview_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
