# Generated by Django 5.1.1 on 2024-11-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0020_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('review', 'Review'), ('interview', 'Interview'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
