# Generated by Django 5.1.1 on 2024-11-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0027_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
