# Generated by Django 5.1 on 2024-09-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('recruiter_name', models.CharField(max_length=100)),
                ('recruiter_email', models.EmailField(max_length=254)),
                ('recruiter_position', models.CharField(max_length=100)),
            ],
        ),
    ]
